/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cl.llanquihuetour.app;
import cl.llanquihuetour.data.GestorPaquetes;
import cl.llanquihuetour.data.GestorPersonas;
import cl.llanquihuetour.data.GestorReservas;

import cl.llanquihuetour.model.Cliente;
import cl.llanquihuetour.model.Direccion;
import cl.llanquihuetour.model.PaqueteTuristico;
import cl.llanquihuetour.model.Reserva;
import cl.llanquihuetour.model.Rut;
import cl.llanquihuetour.model.Tarjeta;
import cl.llanquihuetour.utils.LectorTXT;


import javax.swing.JOptionPane;

/**
 *
 * @author keisi
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public MainPanel() {
        initComponents();
    }
    private GestorPersonas gestorPersonas = new GestorPersonas();
    private GestorPaquetes gestorPaquetes = new GestorPaquetes();
    private GestorReservas gestorReservas = new GestorReservas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        LabelSubtitulo = new javax.swing.JLabel();
        LabelIngresar = new javax.swing.JLabel();
        ComboBoxIngresar = new javax.swing.JComboBox<>();
        txtCampo7 = new javax.swing.JTextField();
        txtCampo8 = new javax.swing.JTextField();
        txtCampo9 = new javax.swing.JTextField();
        lblCampoA = new javax.swing.JLabel();
        lblCampoB = new javax.swing.JLabel();
        lblCampoC = new javax.swing.JLabel();
        lblCampoE = new javax.swing.JLabel();
        lblCampoF = new javax.swing.JLabel();
        lblCampoD = new javax.swing.JLabel();
        lblCampoG = new javax.swing.JLabel();
        lblCampoH = new javax.swing.JLabel();
        lblCampoI = new javax.swing.JLabel();
        lblCampoJ = new javax.swing.JLabel();
        txtCampo1 = new javax.swing.JTextField();
        txtCampo2 = new javax.swing.JTextField();
        txtCampo3 = new javax.swing.JTextField();
        txtCampo5 = new javax.swing.JTextField();
        txtCampo10 = new javax.swing.JTextField();
        txtCampo4 = new javax.swing.JTextField();
        txtCampo6 = new javax.swing.JTextField();
        PanelOpciones1 = new javax.swing.JPanel();
        LabelOpciones = new javax.swing.JLabel();
        ComboBoxOpciones = new javax.swing.JComboBox<>();
        ScrollPanelInfo = new javax.swing.JScrollPane();
        TextAreaInfo = new javax.swing.JTextArea();
        ButtonCargarArchivos = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        PanelGestion = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        LabelTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        LabelTitulo.setText("LLANQUIHUE TOUR");

        LabelSubtitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        LabelSubtitulo.setText("Sistema de gestión turística");

        LabelIngresar.setText("Ingresar:");

        ComboBoxIngresar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Reserva", "Paquete" }));
        ComboBoxIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxIngresarActionPerformed(evt);
            }
        });

        txtCampo7.setColumns(10);

        txtCampo8.setColumns(10);

        txtCampo9.setColumns(10);

        lblCampoA.setText("_____");

        lblCampoB.setText("_____");

        lblCampoC.setText("_____");

        lblCampoE.setText("_____");

        lblCampoF.setText("_____");

        lblCampoD.setText("_____");

        lblCampoG.setText("_____");

        lblCampoH.setText("_____");

        lblCampoI.setText("_____");

        lblCampoJ.setText("_____");

        txtCampo1.setColumns(10);

        txtCampo2.setColumns(10);

        txtCampo3.setColumns(10);

        txtCampo5.setColumns(10);

        txtCampo10.setColumns(10);

        txtCampo4.setColumns(10);

        txtCampo6.setColumns(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSubtitulo)
                            .addComponent(LabelTitulo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCampoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCampoJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCampo1)
                                    .addComponent(txtCampo3)
                                    .addComponent(txtCampo5)
                                    .addComponent(txtCampo4)
                                    .addComponent(txtCampo7)
                                    .addComponent(txtCampo6)
                                    .addComponent(txtCampo8)
                                    .addComponent(txtCampo9)
                                    .addComponent(txtCampo10)
                                    .addComponent(txtCampo2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LabelIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIngresar)
                    .addComponent(ComboBoxIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoA)
                    .addComponent(txtCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoB)
                    .addComponent(txtCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCampoC)
                    .addComponent(txtCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblCampoE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampoD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCampoF)
                    .addComponent(txtCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampoG))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampoH))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoI)
                    .addComponent(txtCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampoJ)
                    .addComponent(txtCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelOpciones1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione una opción:"));

        LabelOpciones.setText("Opciones:");

        ComboBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar Clientes", "Mostrar Reservas", "Mostrar Paquetes" }));
        ComboBoxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOpciones1Layout = new javax.swing.GroupLayout(PanelOpciones1);
        PanelOpciones1.setLayout(PanelOpciones1Layout);
        PanelOpciones1Layout.setHorizontalGroup(
            PanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpciones1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PanelOpciones1Layout.setVerticalGroup(
            PanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpciones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOpciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOpciones)
                    .addComponent(ComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        ScrollPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion:"));

        TextAreaInfo.setColumns(20);
        TextAreaInfo.setRows(5);
        ScrollPanelInfo.setViewportView(TextAreaInfo);

        ButtonCargarArchivos.setText("Cargar Archivos");
        ButtonCargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCargarArchivosActionPerformed(evt);
            }
        });

        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        PanelGestion.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestiones:"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGestionLayout = new javax.swing.GroupLayout(PanelGestion);
        PanelGestion.setLayout(PanelGestionLayout);
        PanelGestionLayout.setHorizontalGroup(
            PanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PanelGestionLayout.setVerticalGroup(
            PanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScrollPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonCargarArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLimpiar)
                    .addComponent(ButtonCargarArchivos)
                    .addComponent(ButtonSalir))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOpcionesActionPerformed
            String opcion = ComboBoxOpciones.getSelectedItem().toString();

    switch (opcion) {

        case "Mostrar Clientes":
            TextAreaInfo.setText(gestorPersonas.listarClientes());
            break;

        case "Mostrar Reservas":
            TextAreaInfo.setText(gestorReservas.listarReservas());
            break;

        case "Mostrar Paquetes":
            TextAreaInfo.setText(gestorPaquetes.listarPaquetes());
            break;
    }
    }//GEN-LAST:event_ComboBoxOpcionesActionPerformed

    private void ComboBoxIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxIngresarActionPerformed
        System.out.println(ComboBoxIngresar.getSelectedItem());

        String opcion = ComboBoxIngresar.getSelectedItem().toString();

        // Mostrar todos por defecto
        lblCampoA.setVisible(true);
        lblCampoB.setVisible(true);
        lblCampoC.setVisible(true);
        lblCampoD.setVisible(true);
        lblCampoE.setVisible(true);
        lblCampoF.setVisible(true);
        lblCampoG.setVisible(true);
        lblCampoH.setVisible(true);
        lblCampoI.setVisible(true);
        lblCampoJ.setVisible(true);

        txtCampo1.setVisible(true);
        txtCampo2.setVisible(true);
        txtCampo3.setVisible(true);
        txtCampo4.setVisible(true);
        txtCampo5.setVisible(true);
        txtCampo6.setVisible(true);
        txtCampo7.setVisible(true);
        txtCampo8.setVisible(true);
        txtCampo9.setVisible(true);
        txtCampo10.setVisible(true);

        if (opcion.equals("Cliente")) {

            lblCampoA.setText("Nombre:");
            lblCampoB.setText("RUT:");
            lblCampoC.setText("Calle:");
            lblCampoD.setText("Número:");
            lblCampoE.setText("Comuna:");
            lblCampoF.setText("Ciudad:");

            lblCampoG.setVisible(false);
            lblCampoH.setVisible(false);
            lblCampoI.setVisible(false);
            lblCampoJ.setVisible(false);

            txtCampo7.setVisible(false);
            txtCampo8.setVisible(false);
            txtCampo9.setVisible(false);
            txtCampo10.setVisible(false);

        } else if (opcion.equals("Paquete")) {

            lblCampoA.setText("Código:");
            lblCampoB.setText("Nombre:");
            lblCampoC.setText("Destino:");
            lblCampoD.setText("Duración:");
            lblCampoE.setText("Lugares:");
            lblCampoF.setText("Transporte:");
            lblCampoG.setText("Horario:");
            lblCampoH.setText("Precio:");
            lblCampoI.setText("Guía:");
            lblCampoJ.setText("Proveedor:");

        } else if (opcion.equals("Reserva")) {

            lblCampoA.setText("Código:");
            lblCampoB.setText("RUT Cliente:");
            lblCampoC.setText("Código Paquete:");
            lblCampoD.setText("Fecha:");
            lblCampoE.setText("Cantidad:");
            lblCampoF.setText("N° Tarjeta:");
            lblCampoG.setText("Titular:");
            lblCampoH.setText("Vencimiento:");

            lblCampoI.setVisible(false);
            lblCampoJ.setVisible(false);

            txtCampo9.setVisible(false);
            txtCampo10.setVisible(false);
        }

    }//GEN-LAST:event_ComboBoxIngresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    String opcion = ComboBoxIngresar.getSelectedItem().toString();

    switch(opcion){

        case "Cliente":
            buscarCliente();
            break;

        case "Paquete":
            buscarPaquete();
            break;

        case "Reserva":
            buscarReserva();
            break;

    }
    }
    private void buscarCliente(){

    String rut = txtCampo2.getText();

    Cliente cliente = gestorPersonas.buscarCliente(rut);

    if (cliente != null) {

        TextAreaInfo.setText(cliente.toString());

    } else {

        TextAreaInfo.setText("Cliente no encontrado.");

    }
}

    private void buscarPaquete(){

    int codigo = Integer.parseInt(txtCampo1.getText());

    PaqueteTuristico paquete = gestorPaquetes.buscarPaquete(codigo);

    if (paquete != null) {

        TextAreaInfo.setText(paquete.toString());

    } else {

        TextAreaInfo.setText("Paquete no encontrado.");

    }

}

    private void buscarReserva(){

    int codigo = Integer.parseInt(txtCampo1.getText());

    Reserva reserva = gestorReservas.buscarReserva(codigo);

    if (reserva != null) {

        TextAreaInfo.setText(reserva.toString());

    } else {

        TextAreaInfo.setText("Reserva no encontrada.");

    }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String opcion = ComboBoxIngresar.getSelectedItem().toString();

    switch(opcion){

        case "Cliente":
            agregarCliente();
            break;

        case "Paquete":
            agregarPaquete();
            break;

        case "Reserva":
            agregarReserva();
            break;

        default:
            JOptionPane.showMessageDialog(this,"Seleccione una opción.");
    }
    }
    private void agregarCliente(){
        
    try {

        String nombre = txtCampo1.getText();
        Rut rut = new Rut(txtCampo2.getText());

        String calle = txtCampo3.getText();
        int numero = Integer.parseInt(txtCampo4.getText());
        String comuna = txtCampo5.getText();
        String ciudad = txtCampo6.getText();

        Direccion direccion = new Direccion(calle, numero, comuna, ciudad);

        Cliente cliente = new Cliente(nombre, rut, direccion);

        gestorPersonas.agregarCliente(cliente);

        TextAreaInfo.setText("Cliente agregado correctamente.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error al agregar cliente.");
    }

}

    private void agregarPaquete(){

    try {

        int codigo = Integer.parseInt(txtCampo1.getText());
        String nombre = txtCampo2.getText();
        String destino = txtCampo3.getText();
        int duracion = Integer.parseInt(txtCampo4.getText());
        String lugares = txtCampo5.getText();
        String transporte = txtCampo6.getText();
        String horario = txtCampo7.getText();
        double precio = Double.parseDouble(txtCampo8.getText());
        String guia = txtCampo9.getText();
        String proveedor = txtCampo10.getText();

        PaqueteTuristico paquete = new PaqueteTuristico(
                codigo,
                nombre,
                destino,
                duracion,
                lugares,
                transporte,
                horario,
                precio,
                guia,
                proveedor
        );

        gestorPaquetes.agregarPaquete(paquete);

        TextAreaInfo.setText("Paquete agregado correctamente.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error al agregar paquete.");

    }

}

    private void agregarReserva(){

    try {

        int codigoReserva = Integer.parseInt(txtCampo1.getText());

        String rutCliente = txtCampo2.getText();
        Cliente cliente = gestorPersonas.buscarCliente(rutCliente);

        if (cliente == null) {
            JOptionPane.showMessageDialog(this,
                    "Cliente no encontrado.");
            return;
        }

        int codigoPaquete = Integer.parseInt(txtCampo3.getText());
        PaqueteTuristico paquete = gestorPaquetes.buscarPaquete(codigoPaquete);

        if (paquete == null) {
            JOptionPane.showMessageDialog(this,
                    "Paquete no encontrado.");
            return;
        }

        String fechaReserva = txtCampo4.getText();
        int cantidadPersonas = Integer.parseInt(txtCampo5.getText());

        String numeroTarjeta = txtCampo6.getText();
        String titular = txtCampo7.getText();
        String fechaVencimiento = txtCampo8.getText();

        Tarjeta tarjeta = new Tarjeta(
                numeroTarjeta,
                titular,
                fechaVencimiento
        );

        Reserva reserva = new Reserva(
                codigoReserva,
                cliente,
                paquete,
                tarjeta,
                fechaReserva,
                cantidadPersonas
        );

        gestorReservas.agregarReserva(reserva);

        TextAreaInfo.setText("Reserva agregada correctamente.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error al agregar reserva.");

    }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed


    String opcion = ComboBoxIngresar.getSelectedItem().toString();

    switch(opcion){

        case "Cliente":
            modificarCliente();
            break;

        case "Paquete":
            modificarPaquete();
            break;

        case "Reserva":
            modificarReserva();
            break;

    }
    }

    private void modificarCliente(){
            try {

        String nombre = txtCampo1.getText();
        Rut rut = new Rut(txtCampo2.getText());

        String calle = txtCampo3.getText();
        int numero = Integer.parseInt(txtCampo4.getText());
        String comuna = txtCampo5.getText();
        String ciudad = txtCampo6.getText();

        Direccion direccion = new Direccion(calle, numero, comuna, ciudad);

        Cliente cliente = new Cliente(nombre, rut, direccion);

        if (gestorPersonas.modificarCliente(rut.toString(), cliente)) {

            TextAreaInfo.setText("Cliente modificado correctamente.");

        } else {

            TextAreaInfo.setText("Cliente no encontrado.");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error al modificar.");

    }

}

    private void modificarPaquete(){
            try {

        int codigo = Integer.parseInt(txtCampo1.getText());

        PaqueteTuristico paquete = new PaqueteTuristico(

                codigo,
                txtCampo2.getText(),
                txtCampo3.getText(),
                Integer.parseInt(txtCampo4.getText()),
                txtCampo5.getText(),
                txtCampo6.getText(),
                txtCampo7.getText(),
                Double.parseDouble(txtCampo8.getText()),
                txtCampo9.getText(),
                txtCampo10.getText()

        );

        if (gestorPaquetes.modificarPaquete(codigo, paquete)) {

            TextAreaInfo.setText("Paquete modificado correctamente.");

        } else {

            TextAreaInfo.setText("Paquete no encontrado.");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error al modificar.");

    }

}

    private void modificarReserva(){
         try {

        int codigo = Integer.parseInt(txtCampo1.getText());

        Cliente cliente = gestorPersonas.buscarCliente(txtCampo2.getText());

        PaqueteTuristico paquete =
                gestorPaquetes.buscarPaquete(Integer.parseInt(txtCampo3.getText()));

        Tarjeta tarjeta = new Tarjeta(

                txtCampo6.getText(),
                txtCampo7.getText(),
                txtCampo8.getText()

        );

        Reserva reserva = new Reserva(

                codigo,
                cliente,
                paquete,
                tarjeta,
                txtCampo4.getText(),
                Integer.parseInt(txtCampo5.getText())

        );

        if (gestorReservas.modificarReserva(codigo, reserva)) {

            TextAreaInfo.setText("Reserva modificada correctamente.");

        } else {

            TextAreaInfo.setText("Reserva no encontrada.");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error al modificar.");

    }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     
    String opcion = ComboBoxIngresar.getSelectedItem().toString();

    switch (opcion) {

        case "Cliente":
            eliminarCliente();
            break;

        case "Paquete":
            eliminarPaquete();
            break;

        case "Reserva":
            eliminarReserva();
            break;
    }
}
private void eliminarCliente(){
     String rut = txtCampo2.getText();

    boolean eliminado = gestorPersonas.eliminarCliente(rut);

    if (eliminado) {

        TextAreaInfo.setText("Cliente eliminado correctamente.");

    } else {

        TextAreaInfo.setText("Cliente no encontrado.");

    }
    

}

private void eliminarPaquete(){
    
    try {

        int codigo = Integer.parseInt(txtCampo1.getText());

        boolean eliminado = gestorPaquetes.eliminarPaquete(codigo);

        if (eliminado) {

            TextAreaInfo.setText("Paquete eliminado correctamente.");

        } else {

            TextAreaInfo.setText("Paquete no encontrado.");

        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Ingrese un código válido.");

    }

}

private void eliminarReserva(){

    try {

        int codigo = Integer.parseInt(txtCampo1.getText());

        boolean eliminado = gestorReservas.eliminarReserva(codigo);

        if (eliminado) {

            TextAreaInfo.setText("Reserva eliminada correctamente.");

        } else {

            TextAreaInfo.setText("Reserva no encontrada.");

        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Ingrese un código válido.");

    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
         
    txtCampo1.setText("");
    txtCampo2.setText("");
    txtCampo3.setText("");
    txtCampo4.setText("");
    txtCampo5.setText("");
    txtCampo6.setText("");
    txtCampo7.setText("");
    txtCampo8.setText("");
    txtCampo9.setText("");
    txtCampo10.setText("");

    TextAreaInfo.setText("");

    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
       
    System.exit(0);

    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonCargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCargarArchivosActionPerformed
        LectorTXT lector = new LectorTXT();
        
        lector.leerClientes("src/main/java/cl/llanquihuetour/files/clientes.txt", gestorPersonas);
        lector.leerPaquetes("src/main/java/cl/llanquihuetour/files/paquetes.txt", gestorPaquetes);
        lector.leerReservas("src/main/java/cl/llanquihuetour/files/reservas.txt", gestorReservas, gestorPersonas, gestorPaquetes);
        
        TextAreaInfo.setText(
                "Carga finalizada.");
        
    }//GEN-LAST:event_ButtonCargarArchivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCargarArchivos;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JComboBox<String> ComboBoxIngresar;
    private javax.swing.JComboBox<String> ComboBoxOpciones;
    private javax.swing.JLabel LabelIngresar;
    private javax.swing.JLabel LabelOpciones;
    private javax.swing.JLabel LabelSubtitulo;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelGestion;
    private javax.swing.JPanel PanelOpciones1;
    private javax.swing.JScrollPane ScrollPanelInfo;
    private javax.swing.JTextArea TextAreaInfo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCampoA;
    private javax.swing.JLabel lblCampoB;
    private javax.swing.JLabel lblCampoC;
    private javax.swing.JLabel lblCampoD;
    private javax.swing.JLabel lblCampoE;
    private javax.swing.JLabel lblCampoF;
    private javax.swing.JLabel lblCampoG;
    private javax.swing.JLabel lblCampoH;
    private javax.swing.JLabel lblCampoI;
    private javax.swing.JLabel lblCampoJ;
    private javax.swing.JTextField txtCampo1;
    private javax.swing.JTextField txtCampo10;
    private javax.swing.JTextField txtCampo2;
    private javax.swing.JTextField txtCampo3;
    private javax.swing.JTextField txtCampo4;
    private javax.swing.JTextField txtCampo5;
    private javax.swing.JTextField txtCampo6;
    private javax.swing.JTextField txtCampo7;
    private javax.swing.JTextField txtCampo8;
    private javax.swing.JTextField txtCampo9;
    // End of variables declaration//GEN-END:variables
}
